name: BuildAndRunTests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
    - crazor/source/**
  pull_request:
    branches: [ "main" ]
    paths:
    - source/**
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout crazor
      uses: actions/checkout@v4
      with:
        path: Crazor

    - name: Checkout adaptivecards
      uses: actions/checkout@v4
      with:
        repository: microsoft/adaptivecards
        path: AdaptiveCards

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore Crazor/source/Crazor.sln

    - name: Build
      run: dotnet build --no-restore Crazor/source/Crazor.sln
      
    - name: Test
      run: dotnet test --no-build --verbosity normal Crazor/source/Crazor.sln
