name: BuildAndRunTests

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    paths:
    - source/**
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: crazor
    - name: Checkout adaptivecards
      uses: actions/checkout@v4
      with:
        repository: microsoft/adaptivecards
        path: adaptivecards
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore crazor/source/Crazor.sln
    - name: Build
      run: dotnet build --no-restore crazor/source/Crazor.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal crazor/source/Crazor.sln
