name: Publish Nuget

on:
  workflow_dispatch:
#  push:
#    branches:
#    - main
#    paths:
#   - source/libraries/**

env:
  DOTNET_VERSION: 8.0.x

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout crazor
        uses: actions/checkout@v4
        with:
          path: crazor
          
      - name: Checkout adaptivecards
        uses: actions/checkout@v4
        with:
          repository: microsoft/adaptivecards
          path: adaptivecards

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Bump build version
        id: bump
        uses: vers-one/dotnet-project-version-updater@v1.5
        with:
          file: |
            "crazor/source/Libraries/Crazor/Crazor.csproj", 
            "crazor/source/Libraries/Crazor.Blazor/Crazor.Blazor.csproj", 
            "crazor/source/Libraries/Crazor.Server/Crazor.Server.csproj", 
            "crazor/source/Libraries/Crazor.Test/Crazor.Test.csproj"
          version: bump-build

      - name: dotnet pack Crazor
        continue-on-error: true
        run: |
          dotnet pack crazor/source/CrazorLibraries.sln -c Debug -o packages --include-symbols --version-suffix "beta" --property WarningLevel=0

      - name: Publish NuGet and symbols
        continue-on-error: true
        id: nuget-push
        uses: edumserrano/nuget-push@v1
        with:
          api-key: '${{ secrets.NUGET_KEY }}' 
          working-directory: 'packages'
        
      - name: Commit version changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Bumped versions'
          add: '*.csproj'
          cwd: './crazor/'
