# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Publish CrazorDemo web app

on:
  push:
    branches:
      - main
    paths:
    - source/libraries/**
    - source/samples/**
  workflow_dispatch:

jobs:
  build:
    # runs-on: windows-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout crazor
        uses: actions/checkout@v4
        with:
          path: Crazor
          
      - name: Checkout adaptivecards
        uses: actions/checkout@v4
        with:
          repository: tomlm/adaptivecards
          path: AdaptiveCards
          ref: main

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore Crazor/source/Crazor.sln 
    
      - name: Build
        run: dotnet build --no-restore Crazor/source/Crazor.sln --property WarningLevel=0 -c Release
    
      - name: dotnet publish
        run: dotnet publish Crazor/source/samples/CrazorBlazorDemo --configuration Release -o Crazor/source/samples/CrazorBlazorDemo/published 

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4.6.2
        with:
          name: .net-app
          path: Crazor/source/samples/CrazorBlazorDemo/published

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0C3E2E79A97F4ED093F8B2EC68C67370 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6FE005B58D824FBFB733D263113B394E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3EBE19E2AF1145D8ACFA03657356A294 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'CrazorDemo'
          slot-name: 'Production'
          package: .
          
