name: Publish Nuget

on:
  workflow_dispatch:
    branches: [ "main" ]


env:
  AZURE_ARTIFACTS_FEED_URL:   https://fuselabs.pkgs.visualstudio.com/c861868a-1061-43d1-8232-ed9ab373867c/_packaging/Crazor/nuget/v3/index.json
  BUILD_CONFIGURATION: 'Debug'    # set this to the appropriate build configuration
  DOTNET_VERSION: '6.x' 

jobs:
  az-artifacts-build-and-deploy:
    runs-on: windows-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v3

      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          source-url: ${{ env.AZURE_ARTIFACTS_FEED_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.AZURE_ARTIFACTS_PAT }} 

      # Run dotnet build and package
      - name: dotnet build and publish
        run: |
          dotnet restore source/libraries/Crazor/Crazor.csproj
          dotnet build -c '${{ env.BUILD_CONFIGURATION }}' source/libraries/Crazor/Crazor.csproj
          dotnet pack -c '${{ env.BUILD_CONFIGURATION }}' --version-suffix beta-$GITHUB_RUN_ID source/libraries/Crazor/Crazor.csproj

      # Publish the package to Azure Artifacts
      - name: 'dotnet publish'
        run: dotnet nuget push --api-key AzureArtifacts source/libraries/Crazor/bin/Release/*.nupkg