name: Publish Nuget

on:
  workflow_dispatch:
#  push:
#    branches:
#    - main
#    paths:
#   - source/libraries/**

env:
  DOTNET_VERSION: 8.0.x

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Get version timestamp
        id: t1
        uses: Kaven-Universe/github-action-current-date-time@v1.1.0
        with:
          format: "YYYYMMDDHHmm"      
      
      - name: Checkout crazor
        uses: actions/checkout@v4
        with:
          path: crazor
          
      - name: Checkout adaptivecards
        uses: actions/checkout@v4
        with:
          repository: microsoft/adaptivecards
          path: adaptivecards

    # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: dotnet pack Crazor
        continue-on-error: true
        run: dotnet pack crazor/source/CrazorLibraries.sln -c Debug -o packages --include-symbols -v d --version-suffix "beta-${{ steps.t1.outputs.time  }}" 

      - name: dotnet push
        run: |
          ls -al packages/*.*nupkg
          # dotnet nuget push --skip-duplicate --api-key ${{secrets.NUGET_KEY}} "packages/crazor*.nupkg"
