name: Publish Nuget

#on:
#  workflow_dispatch:
#    branches: [ "main" ]
on:
  workflow_dispatch:
#  push:
#    branches:
#    - main
#    paths:
#   - source/libraries/**

env:
  DOTNET_VERSION: 8.0.x

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Get version timestamp
        id: t1
        uses: Kaven-Universe/github-action-current-date-time@v1.1.0
        with:
          format: "YYYYMMDDHHmm"      
      
      - name: Checkout crazor
        uses: actions/checkout@v4
        with:
          path: crazor
          
      - name: Checkout adaptivecards
        uses: actions/checkout@v4
        with:
          repository: microsoft/adaptivecards
          path: adaptivecards

    # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore crazor/source/CrazorLibraries.sln

#      - name: Build
#        run: dotnet build --no-restore crazor/source/Crazor.sln

      - name: dotnet pack Crazor
        # run: dotnet pack --no-restore --version-suffix "beta-${{ steps.t1.outputs.time  }}" crazor/source/Crazor.sln
        run: dotnet pack --no-restore --version-suffix "beta-${{ steps.t1.outputs.time  }}" crazor/source/Crazor:Libraries.sln -o packages

      - name: dotnet push
        run: |
          ls -al packages/*.*nupkg
          # dotnet nuget push --api-key ${{secrets.NUGET_KEY}} "crazor/source/libraries/Crazor/bin/Debug/Crazor.*.nupkg"
